#!/usr/bin/env python3
"""Generate EcoFlowLoginKeyData.gen.cpp from secrets/ecoflow/login_key.bin."""

from pathlib import Path
import sys

repo = Path(__file__).resolve().parents[1]
src_bin = repo / "secrets" / "ecoflow" / "login_key.bin"
out_cpp = (
    repo
    / "src"
    / "bridge_ecoflow_delta3"
    / "EcoFlow"
    / "Crypto"
    / "EcoFlowLoginKeyData.gen.cpp"
)

if not src_bin.is_file():
    print(
        "Missing secrets/ecoflow/login_key.bin — generate with "
        "ef-ble-reverse util/login_key_gen.py",
        file=sys.stderr,
    )
    sys.exit(1)

data = src_bin.read_bytes()
expected = 65280
if len(data) != expected:
    print(f"login_key.bin size {len(data)} != {expected}", file=sys.stderr)
    sys.exit(1)

if out_cpp.is_file() and out_cpp.stat().st_mtime >= src_bin.stat().st_mtime:
    print(f"EcoFlow login key embed up to date ({len(data)} bytes)")
    sys.exit(0)

lines = [
    "// AUTO-GENERATED by scripts/embed_ecoflow_login_key.py — do not commit.",
    '#include "EcoFlow/Crypto/EcoFlowLoginKey.h"',
    "",
    "namespace ecoflow::crypto {",
    "",
    f"const uint8_t kEcoFlowLoginKey[{len(data)}] = {{",
]
per_line = 256
for i in range(0, len(data), per_line):
    chunk = data[i : i + per_line]
    body = ",".join(f"0x{b:02x}" for b in chunk)
    suffix = "," if i + per_line < len(data) else ""
    lines.append(f"  {body}{suffix}")
lines += [
    "};",
    "",
    f"const size_t kEcoFlowLoginKeySize = {len(data)};",
    "",
    "}  // namespace ecoflow::crypto",
    "",
]
out_cpp.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Embedded EcoFlow login key -> {out_cpp.relative_to(repo)} ({len(data)} bytes)")
